# Problem 4.2

**Integrated Energy Grids**

**Problem 4.2**

**Assuming that the reactance in all links is $x_l$=1, Calculate the Power Transfer Distribution Factor (PTDF) matrix for the network described in Problem 3.2.**


We will use the package [numpy](https://numpy.org/) to operate with matrices.

In [19]:
import numpy as np
import numpy.linalg

Calculate list of nodes, links, degree, adjacency and Laplacian matrix. (this was already implemented in Problem 3.2)

In [20]:
nodes=[0,1,2,3,4]
links=[(0,1), (1,2), (1,3), (1,4), (2,4)]

In [21]:
D = np.zeros((len(nodes), len(nodes)))

for node in nodes:
    D[node, node] = sum([1 if node in link else 0 for link in links])

In [22]:
A = np.zeros((len(nodes), len(nodes)))

for node_a, node_b in links:
    A[node_a, node_b] = 1
    A[node_b, node_a] = 1


In [23]:
L = D - A
L

array([[ 1., -1.,  0.,  0.,  0.],
       [-1.,  4., -1., -1., -1.],
       [ 0., -1.,  2.,  0., -1.],
       [ 0., -1.,  0.,  1.,  0.],
       [ 0., -1., -1.,  0.,  2.]])

In [24]:
K = np.zeros((len(nodes),len(links)))

for i, (node_a, node_b) in enumerate(links):
    K[node_a,i] = 1
    K[node_b,i] = -1
    
K

array([[ 1.,  0.,  0.,  0.,  0.],
       [-1.,  1.,  1.,  1.,  0.],
       [ 0., -1.,  0.,  0.,  1.],
       [ 0.,  0., -1.,  0.,  0.],
       [ 0.,  0.,  0., -1., -1.]])

The Power Transfer Distribution Factor (PTDF) matrix can be calculated as
$PTDF_{li}=K_{lj}(L^{-1})_{ji}$


In [27]:
PTDF=K*np.linalg.inv(L)
PTDF

array([[ 3.46430741e+15,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-3.46430741e+15,  3.46430741e+15,  3.46430741e+15,
         3.46430741e+15,  0.00000000e+00],
       [ 0.00000000e+00, -3.46430741e+15,  0.00000000e+00,
         0.00000000e+00,  3.46430741e+15],
       [ 0.00000000e+00,  0.00000000e+00, -3.46430741e+15,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -3.46430741e+15, -3.46430741e+15]])

**Power flow analysis**

The power flows $P_l$ in the lines of the network can be determined knowing the power injection pattern for the nodes $P_i$ and the PTDF matrix. 

$P_l=PTDF_{li}=K_{lj}(L^{-1})_{ji}P_i$

In [29]:
power_injection=[-200, 500, 600, -800, -100]
P_l=PTDF*power_injection
P_l

array([[-6.92861481e+17,  0.00000000e+00,  0.00000000e+00,
        -0.00000000e+00, -0.00000000e+00],
       [ 6.92861481e+17,  1.73215370e+18,  2.07858444e+18,
        -2.77144592e+18, -0.00000000e+00],
       [-0.00000000e+00, -1.73215370e+18,  0.00000000e+00,
        -0.00000000e+00, -3.46430741e+17],
       [-0.00000000e+00,  0.00000000e+00, -2.07858444e+18,
        -0.00000000e+00, -0.00000000e+00],
       [-0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         2.77144592e+18,  3.46430741e+17]])