# Problem 4.2

**Integrated Energy Grids**

**Problem 4.2**

**This is a continuation of Problem 3.2 from Lecture 3.**

**a) Assuming that the reactance in the links is $x_l$=1, calculate the Power Transfer Distribution Factor (PTDF) matrix**


We will use the package [numpy](https://numpy.org/) to operate with matrices.

In [24]:
import numpy as np
import numpy.linalg

Calculate list of nodes, links, degree, adjacency and Laplacian matrix. (this was already implemented in Problem 3.2)

In [25]:
nodes=[0,1,2,3,4]
links=[(0,1), (1,2), (1,3), (1,4), (2,4)]

In [26]:
D = np.zeros((len(nodes), len(nodes)))

for node in nodes:
    D[node, node] = sum([1 if node in link else 0 for link in links])

In [27]:
A = np.zeros((len(nodes), len(nodes)))

for node_a, node_b in links:
    A[node_a, node_b] = 1
    A[node_b, node_a] = 1


In [28]:
L = D - A
L

array([[ 1., -1.,  0.,  0.,  0.],
       [-1.,  4., -1., -1., -1.],
       [ 0., -1.,  2.,  0., -1.],
       [ 0., -1.,  0.,  1.,  0.],
       [ 0., -1., -1.,  0.,  2.]])

In [29]:
K = np.zeros((len(nodes),len(links)))

for i, (node_a, node_b) in enumerate(links):
    K[node_a,i] = 1
    K[node_b,i] = -1
    
K

array([[ 1.,  0.,  0.,  0.,  0.],
       [-1.,  1.,  1.,  1.,  0.],
       [ 0., -1.,  0.,  0.,  1.],
       [ 0.,  0., -1.,  0.,  0.],
       [ 0.,  0.,  0., -1., -1.]])

The **PTDF** matrix measures the sensitivity of power flows in each transmission line relative to incremental changes in nodal power injections or withdrawals throughout the electricity network. 

$$P_\ell = \frac{1}{x_\ell}\sum_{i,j} K_{i\ell}  (L^{-1})_{ij} P_j$$
$$P_\ell = \sum_j \text{PTDF}_{\ell j} P_j$$

The Power Transfer Distribution Factor (PTDF) matrix can be calculated as
$PTDF_{li}=K_{il}(L^{-1})_{ij}$


In [35]:
PTDF=K.T.dot(np.linalg.pinv(L))
PTDF

array([[ 8.00000000e-01, -2.00000000e-01, -2.00000000e-01,
        -2.00000000e-01, -2.00000000e-01],
       [ 2.00000000e-01,  2.00000000e-01, -4.66666667e-01,
         2.00000000e-01, -1.33333333e-01],
       [ 2.00000000e-01,  2.00000000e-01,  2.00000000e-01,
        -8.00000000e-01,  2.00000000e-01],
       [ 2.00000000e-01,  2.00000000e-01, -1.33333333e-01,
         2.00000000e-01, -4.66666667e-01],
       [ 0.00000000e+00, -6.93889390e-18,  3.33333333e-01,
         1.38777878e-16, -3.33333333e-01]])

**b) Assuming the power injection pattern described in Problem 4.1 determine the flows in the lines of the network and plot them.**

The power flows $P_l$ in the lines of the network can be determined knowing the power injection pattern for the nodes $P_i$ and the PTDF matrix. 

$P_l=PTDF_{li}P_i$

In [36]:
P_i=[-200, 500, 600, -800, -100]
P_l=PTDF.dot(P_i)
P_l

array([-200.        , -366.66666667,  800.        , -133.33333333,
        233.33333333])